version: '2'
services:
  inewgent_api:
    image: nginx:1.13.0-alpine
    container_name: inewgent_api
    ports:
      - "9000:80"
    volumes:
      - ./inewgent_api:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  inewgent_web:
    image: nginx:1.13.0-alpine
    container_name: inewgent_web
    ports:
      - "9001:80"
    volumes:
      - ./inewgent_web:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  docker_proxy:
    image: nginx
    container_name: docker_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
